language: node_js 

node_js:  
  - node 

services:
  - postgresql

before_script:
  - npm install -g codeclimate-test-reporter
  - psql -c 'drop database if exists hellobooks_test;' -U postgres
  - psql -c 'create database hellobooks_test;' -U postgres
  - psql -c "create user userhello with login password 'ThePassword$';" -U postgres

env:
  - NODE_ENV=test

before_script:  
  - npm install -g codeclimate-test-reporter 
script:  
  - npm test 
after_success:  
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
